# Generated by Django 2.2.5 on 2019-10-06 17:26

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.CharField(choices=[('unsent', 'Unsent'), ('sent', 'Sent')], default='unsent', max_length=100, verbose_name='Status')),
                ('recipient', models.EmailField(max_length=255, verbose_name='Recipient')),
                ('template', models.CharField(blank=True, choices=[('payment_alert', 'Payment Alert'), ('new_payment', 'New Payment'), ('payment_processed', 'Payment Processed')], max_length=255, verbose_name='Subject')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Subject')),
                ('message', models.TextField(blank=True, max_length=255, verbose_name='Message')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Notification Email',
                'verbose_name_plural': 'Notification Emails',
                'ordering': ('-created',),
            },
        ),
    ]
