language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip3 install -r requirements.txt
  - cd ..
  - django-admin.py startproject --template=./condoman --extension=py,md,html,env test_proj
  - cd condoman/src
  - cp condoman/settings/local.sample.env condoman/settings/local.env
  - python manage.py migrate
script:
  - python manage.py test
