# Generated by Django 2.2.5 on 2019-10-03 18:13

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('waiting', 'Waiting for confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('description', models.CharField(max_length=400, verbose_name='Description')),
                ('value', models.DecimalField(decimal_places=2, default='0.0', max_digits=9, verbose_name='Value')),
                ('billing_name', models.CharField(max_length=255, verbose_name='Name')),
                ('billing_address_1', models.CharField(max_length=400, verbose_name='Billing Address 1')),
                ('billing_address_2', models.CharField(blank=True, max_length=400, verbose_name='Billing Address 2')),
                ('billing_postcode', models.CharField(blank=True, max_length=100, verbose_name='Billing Post Code')),
                ('billing_city', models.CharField(blank=True, max_length=100, verbose_name='Billing City / Region')),
                ('billing_country', models.CharField(blank=True, max_length=400, verbose_name='Billing Country')),
                ('billing_vat_number', models.CharField(max_length=9, verbose_name='VAT number')),
                ('extra_data', models.TextField(blank=True, default='', verbose_name='Extra Data')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
