# Generated by Django 2.2.5 on 2019-10-03 18:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_auto_20191003_1914'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExemptDue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.UUIDField(default=uuid.uuid4, verbose_name='Slug')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exemptdue_dues', to='payments.Payment')),
                ('proprietor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exemptdue_dues', to='profiles.ProprietorProfile')),
            ],
            options={
                'verbose_name': 'Exempt Due',
                'verbose_name_plural': 'Exempt Dues',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='BankTransferDue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.UUIDField(default=uuid.uuid4, verbose_name='Slug')),
                ('image', models.ImageField(null=True, upload_to='dues/%Y-%m-%d/', verbose_name='Image')),
                ('payment_date_limit', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Payment Date Limit')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banktransferdue_dues', to='payments.Payment')),
                ('proprietor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banktransferdue_dues', to='profiles.ProprietorProfile')),
            ],
            options={
                'verbose_name': 'Bank Transfer Due',
                'verbose_name_plural': 'Bank Transfer Dues',
                'ordering': ('-created',),
            },
        ),
    ]
