# Generated by Django 2.2.5 on 2019-09-25 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtools', '0003_auto_20160128_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProprietorProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('slug', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('vat_number', models.CharField(help_text='Please ensure this number is correct', max_length=100, verbose_name='Phone')),
                ('notes', models.TextField(help_text='Internal Notes. Not publicly available', verbose_name='Internal Notes')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email verified')),
                ('fraction', models.CharField(max_length=100, verbose_name='Fraction')),
                ('apartment_number', models.CharField(max_length=100, verbose_name='Apartment no.')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Phone')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
