# Generated by Django 2.2.5 on 2019-10-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietorprofile',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal Notes. Not publicly available', verbose_name='Internal Notes'),
        ),
        migrations.AlterField(
            model_name='proprietorprofile',
            name='vat_number',
            field=models.IntegerField(help_text='Please ensure this number is correct. Numbers only', null=True, verbose_name='VAT Number'),
        ),
    ]
