# Generated by Django 2.2.5 on 2019-10-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
        ('profiles', '0003_auto_20191003_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proprietorprofile',
            name='apartment_number',
        ),
        migrations.RemoveField(
            model_name='proprietorprofile',
            name='fraction',
        ),
        migrations.AddField(
            model_name='proprietorprofile',
            name='apartment',
            field=models.ForeignKey(null=True, on_delete='Apartment', to='apartments.Apartment'),
        ),
    ]
