# Generated by Django 2.2.5 on 2019-10-06 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20191006_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietorprofile',
            name='vat_number',
            field=models.CharField(help_text='Please ensure this number is correct. Numbers only', max_length=9, null=True, validators=[django.core.validators.MinLengthValidator(9)], verbose_name='VAT Number'),
        ),
    ]
