# Generated by Django 2.2.5 on 2019-10-03 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condofigurations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condominiumconfiguration',
            name='condominium_payment_day',
        ),
        migrations.AddField(
            model_name='condominiumconfiguration',
            name='address_1',
            field=models.CharField(default='Sample Address 1', max_length=400, verbose_name='Address 1'),
        ),
        migrations.AddField(
            model_name='condominiumconfiguration',
            name='address_2',
            field=models.CharField(blank=True, max_length=400, verbose_name='Address 2'),
        ),
        migrations.AddField(
            model_name='condominiumconfiguration',
            name='city',
            field=models.CharField(default='Sample City', max_length=100, verbose_name='City / Region'),
        ),
        migrations.AddField(
            model_name='condominiumconfiguration',
            name='condominium_fee_description',
            field=models.CharField(default='Condominium Fees', help_text='Description for Invoices', max_length=255, verbose_name='Condominium Fee Description'),
        ),
        migrations.AddField(
            model_name='condominiumconfiguration',
            name='country',
            field=models.CharField(default='Portugal', max_length=400, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='condominiumconfiguration',
            name='payment_issue_day',
            field=models.PositiveSmallIntegerField(default=1, help_text='Day in the month where payment must be issued to a proprietor.             Choose a value from 1 to 27 in order to avoid issues with leaping years', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(27)], verbose_name='Payment Issuing Day'),
        ),
        migrations.AddField(
            model_name='condominiumconfiguration',
            name='payment_issue_day_limit',
            field=models.PositiveSmallIntegerField(default=5, help_text='Number of days a due needs to be paid, including. User will be alerted once that moment passes.<br />            If Payment Issuing Day is set to August 4 and the payment limit is set to 5, the proprietor will             be alerted in August 10.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Payment Limit'),
        ),
        migrations.AddField(
            model_name='condominiumconfiguration',
            name='postcode',
            field=models.CharField(default='Sample Postcode', max_length=100, verbose_name='Post Code'),
        ),
    ]
