# Generated by Django 2.2.5 on 2019-10-06 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condofigurations', '0002_auto_20191003_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condominiumconfiguration',
            name='condominium_fee',
        ),
        migrations.RemoveField(
            model_name='condominiumconfiguration',
            name='condominium_fee_description',
        ),
    ]
