# Generated by Django 2.2.5 on 2019-10-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraction', models.CharField(max_length=100, verbose_name='Fraction')),
                ('floor', models.CharField(max_length=100, verbose_name='Floor')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('condominium_fee', models.DecimalField(decimal_places=2, default='10.0', help_text='Value in Euros', max_digits=9, verbose_name='Condominium Fee')),
                ('order', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Apartment',
                'verbose_name_plural': 'Apartments',
                'ordering': ('order', 'fraction'),
            },
        ),
    ]
