# Generated by Django 2.2.5 on 2019-10-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='condominium_fee_description',
            field=models.CharField(default='Condominium Fees', help_text='Description for Invoices', max_length=400, verbose_name='Condominium Fee Description'),
        ),
    ]
